### ISSUE TITLE
[Feature Request] Output Selection in Flake Format

### ISSUE THREAD

**Issue by gs-101** [3timeslazy/nix-search-tv#1]
Currently, whatever package one selects from the search is inserted in this "source/ package" format:

```sh
nix shell nixpkgs/ emacs
```

Because that's what appears in the search.

Wouldn't it be more useful if either the Flake format or the package format were to be used instead?

```sh
# Flake format
nix shell nixpkgs#emacs
# Package format
nix shell -p emacs
```

**Comment by 3timeslazy** [comment]
Hi @gs-101,

May I ask what problem you're trying to solve?

My guess it that you're trying to use nix-search-tv for shell completion? If so, I have a bad-but-works-for-me solution. I use zsh with[ fzf-tab](https://github.com/Aloxaf/fzf-tab) plugin. In my zshrc I add `zstyle ':fzf-tab:complete:nix-shell:*' fzf-preview 'nix-search-tv preview --indexes nixpkgs $word'`, which add preview to all completions. Like below

![Image](https://github.com/user-attachments/assets/fad45b92-a518-462d-89a4-bb047324a5ce)

The problem is that it also adds preview to the rest of commands/options, like so

![Image](https://github.com/user-attachments/assets/951fd345-f71a-4e5b-b41d-0a8991d956e0)

I tried playing with zstyle (like `zstyle ':fzf-tab:complete:nix-shell:option-p'`), but couldn't get it work.

Two more problems with that are:

**1/** nix-search-tv index might not be consistent with the package in channel, if you specify any. So the version in the preview might differ from the version that will be installed.

But again, works for me

**2/** arguments to `nix-shell -p` and packages in nixpkgs are different. 

Like, `bitwarden_rs` is a valid argument for nix-shell, but you won't find it at [nixpkgs search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=bitwarden_rs)

![Image](https://github.com/user-attachments/assets/8e1855c9-4a84-424e-8695-35c2709a1380)

This is due to [`bitwarden_rs` being renamed to `vaultwarden`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix#L370).

Somewhere in my git stash I even have a simple change that parses the aliases.nix file, extracts aliases and throw messages with a couple of regexps and renders the new package name/throw message, but haven't pushed it yet (and not sure if I should though)

**Comment by gs-101** [comment]
> Hi [@gs-101](https://github.com/gs-101),
> 
> May I ask what problem you're trying to solve?

Sorry about that, seems like I wasn't clear enough.

> My guess it that you're trying to use nix-search-tv for shell completion?

Exactly that, to complete for a package using [tv](https://github.com/alexpasmantier/television).

I'm asking for this here because I can so perfectly fine with [my setup for Guix](https://github.com/alexpasmantier/television/wiki/Cable-channels#%EF%B8%8F-guix):

```toml
[[cable_channel]]
name = "guix-packages"
# The extra commands here remove all extra fields, leaving only the package's name left.
# That way, you can use tv for completion.
source_command = "guix package --list-available=.* | cut -f 1 | tr -d [:blank:]"
preview_command = "guix package --show={0}"
```

![Search for the Emacs package in Guix using tv](https://github.com/user-attachments/assets/2d3d4297-74b1-47c7-a018-54b2ca01e33d)

![Successful Guix shell for Emacs, because the output is formated correctly (only the package's name)](https://github.com/user-attachments/assets/bc59edc0-2fa2-40fc-b067-c6036f6eda34)

Here is what is happening for me in tv: when searching for a package, results show up like `SOURCE/ PACKAGE`

![Search for the Emacs package in Nix using tv](https://github.com/user-attachments/assets/1e67a20f-8778-47be-bc53-689d850f1a9b)

This is not that much of an issue if you're only searching, but if you select the item you want with `RET` (`Enter`) for completion:

![Failed Nix shell for Emacs, because the output is formatted incorrectly](https://github.com/user-attachments/assets/95add577-635e-4d67-97f8-ec7d823e4e78)

I think that just changing [this](https://github.com/3timeslazy/nix-search-tv/blob/2068e08314c2f01cc99d9bb8db53030dc9bb8ad3/cmd/index.go#L62) line to this:

```go
func addIndexPrefix(index, pkg string) string {
	return index + "#" + pkg
}
```

Fixes the issue.

**Comment by 3timeslazy** [comment]
@gs-101, as I  my zsh example above, I'd recommend you adding "--indexes nixpkgs" to the command, so that the tool will only search for nixpkgs and since it only looks for single source, I'll not print the prefix

```toml
[[cable_channel]]
name = "nixpkgs"
source_command = "nix-search-tv print --indexes nixpkgs"
preview_command = "nix-search-tv preview --indexes nixpkgs {}"
```

**Comment by gs-101** [comment]
Thanks, I read through your zsh + fzf but it's a different setup from what I have (bash + tv) so I thought it wouldn't work.

Searching only for nixpkgs is fine. I have [NUR](https://github.com/nix-community/NUR) installed but I don't even know what's in there :v.

I'll try it out later (after updating my system) to see if there's any issues before closing this.

**Comment by gs-101** [comment]
@3timeslazy Thank you, fixed this with a nice `sed` incantation:

```toml
[[cable_channel]]
name = "nixpkgs"
source_command = "nix-search-tv print --indexes nixpkgs | sed \"s/^/nixpkgs#/\"" # Prefix output with "nixpkgs#"
preview_command = "nix-search-tv preview --indexes nixpkgs {}"
```

From the comment you left in the function, I think I could even replace the hardcoded `nixpkgs#` with another command to get the index.
